language: python

python:
  - "3.4"

env:
  - CODECOV_TOKEN="eb8922cf-a9e1-4d68-b5ab-d8bc20ad9900"

install:
  - pip install codecov
  - pip install -r requirements.txt
  - pip install .

script:
  - python setup.py test
  - codecov
