language: python

python:
  - "3.4"

env:
  global:
    - CODECOV_TOKEN="eb8922cf-a9e1-4d68-b5ab-d8bc20ad9900"
    - NAME="sensapp-storage"
  
services:
  - docker
  
install:
  - pip install codecov coverage
  - pip install -r requirements.txt
  - pip install .

script:
  - python setup.py test
  - coverage run setup.py test
  - codecov

after_success:
  - |
    if [[ "$TRAVIS_TAG" =~ "^v" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker build -t $DOCKER_USERNAME/$NAME -f Dockerfile . ;
      docker tag $DOCKER_USERNAME/$NAME $DOCKER_NAME/$NAME:$TRAVIS_TAG ;
      docker tag $DOCKER_USERNAME/$NAME $DOCKER_NAME/$NAME:latest ;
      docker push $DOCKER_NAME/$NAME ;
    fi
